eval:
  mode: loose
  tolerance: 0.05

metrics:
  prob_threshold: 0.15
  prob_threshold_onset: 0.15
  prob_threshold_offset: 0.15
  aggregation:
    mode: k_of_p
    k:
      onset: 1
      offset: 1
